### ISSUE TITLE
matt you broke everything naughty

### ISSUE THREAD

**Issue by kurokuno** [Mattabase/MattaCraft-1.7#6]
1. coils from thermal expansion have no recipie
2. seared brick can not be made molten so no tinkers steel works
   florbs press you can make the one that has tinkers textures however you require the one that has IE textures
3. you can now make gear casts and gears in tinkers
4. matts still a butt because of cursed earth .
5. left the easy recipe on for RF tools frames
6. EnderIO is on easy mode

**Comment by Mattabase** [comment]
1. Refer To #8 
2.  Working On It
3. ^
4. Fixed
5. Fixed
6. Fixed
